# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghs < Formula
  desc "a npx-like script execution for gists"
  homepage "https://github.com/flexwie/ghs"
  version "0.3"
  license "MIT"

  depends_on "gh"

  on_macos do
    url "https://github.com/flexwie/ghs/releases/download/v0.3/ghs_0.3_darwin_all.tar.gz"
    sha256 "08f6ecdef2a883868758e9ef0ff7923881afa551941e4e63d70130d42477bac9"

    def install
      bin.install "ghs"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/flexwie/ghs/releases/download/v0.3/ghs_0.3_linux_amd64.tar.gz"
        sha256 "22d9f1f1872deebf82b5befbb5b421ccd231e7441665ae313b6e34ace05b529a"

        def install
          bin.install "ghs"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/flexwie/ghs/releases/download/v0.3/ghs_0.3_linux_arm64.tar.gz"
        sha256 "c15e1dd61594e6380dce2ed2078eb320ab80446c8c10244b3093618daabb14d7"

        def install
          bin.install "ghs"
        end
      end
    end
  end
end
